package com.oa.demo.qsy.pojo;

public class BaseArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_area.AREA_PRI_ID
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    private Long areaPriId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_area.AREA_ID
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    private String areaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_area.AREA_TYPE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    private String areaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_area.AREA_NAME
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_area.AREA_SHORT_NAME
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    private String areaShortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_area.LONGITUDE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_area.LATITUDE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    private String latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_area.AREA_PRI_ID
     *
     * @return the value of base_area.AREA_PRI_ID
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public Long getAreaPriId() {
        return areaPriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_area.AREA_PRI_ID
     *
     * @param areaPriId the value for base_area.AREA_PRI_ID
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public void setAreaPriId(Long areaPriId) {
        this.areaPriId = areaPriId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_area.AREA_ID
     *
     * @return the value of base_area.AREA_ID
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public String getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_area.AREA_ID
     *
     * @param areaId the value for base_area.AREA_ID
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_area.AREA_TYPE
     *
     * @return the value of base_area.AREA_TYPE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public String getAreaType() {
        return areaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_area.AREA_TYPE
     *
     * @param areaType the value for base_area.AREA_TYPE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_area.AREA_NAME
     *
     * @return the value of base_area.AREA_NAME
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_area.AREA_NAME
     *
     * @param areaName the value for base_area.AREA_NAME
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_area.AREA_SHORT_NAME
     *
     * @return the value of base_area.AREA_SHORT_NAME
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public String getAreaShortName() {
        return areaShortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_area.AREA_SHORT_NAME
     *
     * @param areaShortName the value for base_area.AREA_SHORT_NAME
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public void setAreaShortName(String areaShortName) {
        this.areaShortName = areaShortName == null ? null : areaShortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_area.LONGITUDE
     *
     * @return the value of base_area.LONGITUDE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_area.LONGITUDE
     *
     * @param longitude the value for base_area.LONGITUDE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_area.LATITUDE
     *
     * @return the value of base_area.LATITUDE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_area.LATITUDE
     *
     * @param latitude the value for base_area.LATITUDE
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }
}