package com.oa.demo.qsy.pojo;

import java.util.Date;

public class SysLeavebill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.id
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.days
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    private Integer days;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.content
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.remark
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.leaveDate
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    private Date leavedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.state
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_leavebill.user_id
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.id
     *
     * @return the value of sys_leavebill.id
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.id
     *
     * @param id the value for sys_leavebill.id
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.days
     *
     * @return the value of sys_leavebill.days
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public Integer getDays() {
        return days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.days
     *
     * @param days the value for sys_leavebill.days
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public void setDays(Integer days) {
        this.days = days;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.content
     *
     * @return the value of sys_leavebill.content
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.content
     *
     * @param content the value for sys_leavebill.content
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.remark
     *
     * @return the value of sys_leavebill.remark
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.remark
     *
     * @param remark the value for sys_leavebill.remark
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.leaveDate
     *
     * @return the value of sys_leavebill.leaveDate
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public Date getLeavedate() {
        return leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.leaveDate
     *
     * @param leavedate the value for sys_leavebill.leaveDate
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public void setLeavedate(Date leavedate) {
        this.leavedate = leavedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.state
     *
     * @return the value of sys_leavebill.state
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.state
     *
     * @param state the value for sys_leavebill.state
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_leavebill.user_id
     *
     * @return the value of sys_leavebill.user_id
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_leavebill.user_id
     *
     * @param userId the value for sys_leavebill.user_id
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}