package com.oa.demo.qsy.pojo;

import java.util.Date;

public class SysOrg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_ID
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private Long orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_PARENT_ID
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private Long orgParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.IS_PARENT
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private Short isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_NAME
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private String orgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_PATH
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private String orgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.ORG_DESC
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private String orgDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.DISP_INDEX
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private Short dispIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.STATE
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private Short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_org.CREATED_DATE
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    private Date createdDate;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_ID
     *
     * @return the value of sys_org.ORG_ID
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_ID
     *
     * @param orgId the value for sys_org.ORG_ID
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_PARENT_ID
     *
     * @return the value of sys_org.ORG_PARENT_ID
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public Long getOrgParentId() {
        return orgParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_PARENT_ID
     *
     * @param orgParentId the value for sys_org.ORG_PARENT_ID
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setOrgParentId(Long orgParentId) {
        this.orgParentId = orgParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.IS_PARENT
     *
     * @return the value of sys_org.IS_PARENT
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public Short getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.IS_PARENT
     *
     * @param isParent the value for sys_org.IS_PARENT
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setIsParent(Short isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_NAME
     *
     * @return the value of sys_org.ORG_NAME
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_NAME
     *
     * @param orgName the value for sys_org.ORG_NAME
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_PATH
     *
     * @return the value of sys_org.ORG_PATH
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public String getOrgPath() {
        return orgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_PATH
     *
     * @param orgPath the value for sys_org.ORG_PATH
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setOrgPath(String orgPath) {
        this.orgPath = orgPath == null ? null : orgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.ORG_DESC
     *
     * @return the value of sys_org.ORG_DESC
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public String getOrgDesc() {
        return orgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.ORG_DESC
     *
     * @param orgDesc the value for sys_org.ORG_DESC
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setOrgDesc(String orgDesc) {
        this.orgDesc = orgDesc == null ? null : orgDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.DISP_INDEX
     *
     * @return the value of sys_org.DISP_INDEX
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public Short getDispIndex() {
        return dispIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.DISP_INDEX
     *
     * @param dispIndex the value for sys_org.DISP_INDEX
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setDispIndex(Short dispIndex) {
        this.dispIndex = dispIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.STATE
     *
     * @return the value of sys_org.STATE
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.STATE
     *
     * @param state the value for sys_org.STATE
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.CREATED_DATE
     *
     * @return the value of sys_org.CREATED_DATE
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.CREATED_DATE
     *
     * @param createdDate the value for sys_org.CREATED_DATE
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

	@Override
	public String toString() {
		return "SysOrg [orgId=" + orgId + ", orgParentId=" + orgParentId + ", isParent=" + isParent + ", orgName="
				+ orgName + ", orgPath=" + orgPath + ", orgDesc=" + orgDesc + ", dispIndex=" + dispIndex + ", state="
				+ state + ", createdDate=" + createdDate + "]";
	}
    
    
}