package com.oa.demo.qsy.pojo;

import java.util.Date;

public class SysRoleMenuRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu_rel.ROLE_MENU_REL
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    private Long roleMenuRel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu_rel.ROLE_ID
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu_rel.MENU_ID
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    private Long menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu_rel.CREATED_DATE
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu_rel.ROLE_MENU_REL
     *
     * @return the value of sys_role_menu_rel.ROLE_MENU_REL
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public Long getRoleMenuRel() {
        return roleMenuRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu_rel.ROLE_MENU_REL
     *
     * @param roleMenuRel the value for sys_role_menu_rel.ROLE_MENU_REL
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public void setRoleMenuRel(Long roleMenuRel) {
        this.roleMenuRel = roleMenuRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu_rel.ROLE_ID
     *
     * @return the value of sys_role_menu_rel.ROLE_ID
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu_rel.ROLE_ID
     *
     * @param roleId the value for sys_role_menu_rel.ROLE_ID
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu_rel.MENU_ID
     *
     * @return the value of sys_role_menu_rel.MENU_ID
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu_rel.MENU_ID
     *
     * @param menuId the value for sys_role_menu_rel.MENU_ID
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu_rel.CREATED_DATE
     *
     * @return the value of sys_role_menu_rel.CREATED_DATE
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu_rel.CREATED_DATE
     *
     * @param createdDate the value for sys_role_menu_rel.CREATED_DATE
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}