package com.oa.demo.qsy.pojo.mapper;

import com.oa.demo.qsy.pojo.BaseAreaRel;
import com.oa.demo.qsy.pojo.BaseAreaRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseAreaRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    long countByExample(BaseAreaRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int deleteByExample(BaseAreaRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int deleteByPrimaryKey(Long areaRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int insert(BaseAreaRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int insertSelective(BaseAreaRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    List<BaseAreaRel> selectByExample(BaseAreaRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    BaseAreaRel selectByPrimaryKey(Long areaRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") BaseAreaRel record, @Param("example") BaseAreaRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int updateByExample(@Param("record") BaseAreaRel record, @Param("example") BaseAreaRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int updateByPrimaryKeySelective(BaseAreaRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    int updateByPrimaryKey(BaseAreaRel record);
}