package com.oa.demo.qsy.pojo.mapper;

import com.oa.demo.qsy.pojo.BaseArea;
import com.oa.demo.qsy.pojo.BaseAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    long countByExample(BaseAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int deleteByExample(BaseAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int deleteByPrimaryKey(Long areaPriId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int insert(BaseArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int insertSelective(BaseArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    List<BaseArea> selectByExample(BaseAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    BaseArea selectByPrimaryKey(Long areaPriId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") BaseArea record, @Param("example") BaseAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int updateByExample(@Param("record") BaseArea record, @Param("example") BaseAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int updateByPrimaryKeySelective(BaseArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area
     *
     * @mbg.generated Tue Jan 16 14:22:51 CST 2018
     */
    int updateByPrimaryKey(BaseArea record);

	List<BaseArea> selectBaseAreaByCondition(String areaParentId);
}