package com.oa.demo.qsy.pojo.mapper;

import com.oa.demo.qsy.pojo.SysLeavebill;
import com.oa.demo.qsy.pojo.SysLeavebillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysLeavebillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    long countByExample(SysLeavebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int deleteByExample(SysLeavebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int insert(SysLeavebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int insertSelective(SysLeavebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    List<SysLeavebill> selectByExample(SysLeavebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    SysLeavebill selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysLeavebill record, @Param("example") SysLeavebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int updateByExample(@Param("record") SysLeavebill record, @Param("example") SysLeavebillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int updateByPrimaryKeySelective(SysLeavebill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_leavebill
     *
     * @mbg.generated Wed Jan 24 14:16:53 CST 2018
     */
    int updateByPrimaryKey(SysLeavebill record);
}