package com.oa.demo.qsy.pojo.mapper;

import com.oa.demo.qsy.common.pojo.org.SysOrgSub;
import com.oa.demo.qsy.pojo.SysOrg;
import com.oa.demo.qsy.pojo.SysOrgExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysOrgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    long countByExample(SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int deleteByExample(SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int deleteByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int insert(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int insertSelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    List<SysOrg> selectByExample(SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    SysOrg selectByPrimaryKey(Long orgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysOrg record, @Param("example") SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int updateByExample(@Param("record") SysOrg record, @Param("example") SysOrgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int updateByPrimaryKeySelective(SysOrg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_org
     *
     * @mbg.generated Thu Jan 04 14:14:29 CST 2018
     */
    int updateByPrimaryKey(SysOrg record);
    
    
    List<SysOrgSub> queryOrgList(Map<String, Object> param);
    
    int getOrgCount();

	SysOrgSub selectOrgInfo(Long orgId);

	long countByOrgCondition(Map<String, Object> param);
}