package com.oa.demo.qsy.pojo.mapper;

import com.oa.demo.qsy.pojo.SysRoleUserRel;
import com.oa.demo.qsy.pojo.SysRoleUserRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleUserRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    long countByExample(SysRoleUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int deleteByExample(SysRoleUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int deleteByPrimaryKey(Long roleUserRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int insert(SysRoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int insertSelective(SysRoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    List<SysRoleUserRel> selectByExample(SysRoleUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    SysRoleUserRel selectByPrimaryKey(Long roleUserRelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRoleUserRel record, @Param("example") SysRoleUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int updateByExample(@Param("record") SysRoleUserRel record, @Param("example") SysRoleUserRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleUserRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user_rel
     *
     * @mbg.generated Wed Jan 17 11:02:13 CST 2018
     */
    int updateByPrimaryKey(SysRoleUserRel record);
}