package com.oa.demo.qsy.pojo.mapper;

import com.oa.demo.qsy.pojo.SysRoleMenuRel;
import com.oa.demo.qsy.pojo.SysRoleMenuRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleMenuRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    long countByExample(SysRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int deleteByExample(SysRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int deleteByPrimaryKey(Long roleMenuRel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int insert(SysRoleMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int insertSelective(SysRoleMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    List<SysRoleMenuRel> selectByExample(SysRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    SysRoleMenuRel selectByPrimaryKey(Long roleMenuRel);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysRoleMenuRel record, @Param("example") SysRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int updateByExample(@Param("record") SysRoleMenuRel record, @Param("example") SysRoleMenuRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int updateByPrimaryKeySelective(SysRoleMenuRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_menu_rel
     *
     * @mbg.generated Thu Jan 18 16:35:22 CST 2018
     */
    int updateByPrimaryKey(SysRoleMenuRel record);
}