package com.oa.demo.qsy.pojo;

import java.util.ArrayList;
import java.util.List;

public class BaseAreaRelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public BaseAreaRelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAreaRelIdIsNull() {
            addCriterion("AREA_REL_ID is null");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdIsNotNull() {
            addCriterion("AREA_REL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdEqualTo(Long value) {
            addCriterion("AREA_REL_ID =", value, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdNotEqualTo(Long value) {
            addCriterion("AREA_REL_ID <>", value, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdGreaterThan(Long value) {
            addCriterion("AREA_REL_ID >", value, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("AREA_REL_ID >=", value, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdLessThan(Long value) {
            addCriterion("AREA_REL_ID <", value, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdLessThanOrEqualTo(Long value) {
            addCriterion("AREA_REL_ID <=", value, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdIn(List<Long> values) {
            addCriterion("AREA_REL_ID in", values, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdNotIn(List<Long> values) {
            addCriterion("AREA_REL_ID not in", values, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdBetween(Long value1, Long value2) {
            addCriterion("AREA_REL_ID between", value1, value2, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaRelIdNotBetween(Long value1, Long value2) {
            addCriterion("AREA_REL_ID not between", value1, value2, "areaRelId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNull() {
            addCriterion("AREA_ID is null");
            return (Criteria) this;
        }

        public Criteria andAreaIdIsNotNull() {
            addCriterion("AREA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaIdEqualTo(String value) {
            addCriterion("AREA_ID =", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotEqualTo(String value) {
            addCriterion("AREA_ID <>", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThan(String value) {
            addCriterion("AREA_ID >", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_ID >=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThan(String value) {
            addCriterion("AREA_ID <", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLessThanOrEqualTo(String value) {
            addCriterion("AREA_ID <=", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdLike(String value) {
            addCriterion("AREA_ID like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotLike(String value) {
            addCriterion("AREA_ID not like", value, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdIn(List<String> values) {
            addCriterion("AREA_ID in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotIn(List<String> values) {
            addCriterion("AREA_ID not in", values, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdBetween(String value1, String value2) {
            addCriterion("AREA_ID between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaIdNotBetween(String value1, String value2) {
            addCriterion("AREA_ID not between", value1, value2, "areaId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdIsNull() {
            addCriterion("AREA_PARENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdIsNotNull() {
            addCriterion("AREA_PARENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdEqualTo(String value) {
            addCriterion("AREA_PARENT_ID =", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdNotEqualTo(String value) {
            addCriterion("AREA_PARENT_ID <>", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdGreaterThan(String value) {
            addCriterion("AREA_PARENT_ID >", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdGreaterThanOrEqualTo(String value) {
            addCriterion("AREA_PARENT_ID >=", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdLessThan(String value) {
            addCriterion("AREA_PARENT_ID <", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdLessThanOrEqualTo(String value) {
            addCriterion("AREA_PARENT_ID <=", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdLike(String value) {
            addCriterion("AREA_PARENT_ID like", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdNotLike(String value) {
            addCriterion("AREA_PARENT_ID not like", value, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdIn(List<String> values) {
            addCriterion("AREA_PARENT_ID in", values, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdNotIn(List<String> values) {
            addCriterion("AREA_PARENT_ID not in", values, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdBetween(String value1, String value2) {
            addCriterion("AREA_PARENT_ID between", value1, value2, "areaParentId");
            return (Criteria) this;
        }

        public Criteria andAreaParentIdNotBetween(String value1, String value2) {
            addCriterion("AREA_PARENT_ID not between", value1, value2, "areaParentId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_area_rel
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 16 14:22:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table base_area_rel
     *
     * @mbg.generated Tue Jan 16 14:22:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}